### PR TITLE
- fix /me messages were not being posted

### PR DESCRIPTION
**Pull request by edmz**

### CODE REVIEW

**Comment by edmz** [comment]
i suck at PRs.

Somehow 3 commits ended up as one.

Is this OK?

**Comment by edmz** [comment]
initial emoji support got mixed with the /me parts

**Comment by HashNuke** [comment]
That's ok. Next time you can work on different branches. For this one just
send a PR. We'll sort this out :-)

**Comment by HashNuke** [comment]
Oh and send it to the dev branch. I haven't merged that with the master
(get some errors in Heroku. So have to fix that before merging to master).

**Pull request closed without merging**
